---
- hosts: all
  user: vagrant
  gather_facts: False
  sudo: no
  vars:
    - username: vagrant
    - home_dir: "/home/{{ username }}"
  tasks:
    - name: python stuff
      apt: name={{ item }} cache_valid_time=3600 state=installed update_cache=yes
      sudo: yes
      with_items:
        - python
        - python-pip
    - name: pip stuff
      pip: name={{ item }} state=present
      sudo: yes
      with_items:
        - virtualenv
    - include: ansible-vim/vim.yml
